## Retrieving ensemble input data from MARS

This notebook demonstrates how the input data used in the "ensemble.ipynb" notebook was generated.

In [1]:
import earthkit.data as ekd
from earthkit.data import from_source
from earthkit.data import FieldList

params = [
    {"param": "10fg3", "levtype": "sfc"},
    {"param": "z", "levtype": "pl", "levelist": 850},
]

d_common = {
     "date": 20131025,
     "time": 0,
     "step": [72, 78, 84],
     "grid": [0.75, 0.75],
     "area": [66, -19.5, 43.5, 15.75]
     }

ds_fc = FieldList()
ds_en = FieldList()
for p in params:
    # hires deterministic forecast
    ds_fc += from_source("mars", dict(**d_common, **p, type="fc"))

    # control ENS forecast
    ds_en += from_source("mars", dict(**d_common, **p, stream="enfo", type="cf"))

    # perturbed ENS forecast
    ds_en += from_source("mars", dict(**d_common, **p, stream="enfo", type="pf", number=[1,"TO", 50]))
    

# save data to disk
ds_fc.to_target("file", "fc_storm_st_jude.grib")
ds_en.to_target("file", "ens_storm_st_jude.grib")

In [2]:
ds_fc.ls()

,centre,shortName,typeOfLevel,level,dataDate,dataTime,stepRange,dataType,number,gridType
0,ecmf,10fg3,surface,0,20131025,0,69-72,fc,0,regular_ll
1,ecmf,10fg3,surface,0,20131025,0,75-78,fc,0,regular_ll
2,ecmf,10fg3,surface,0,20131025,0,81-84,fc,0,regular_ll
3,ecmf,z,isobaricInhPa,850,20131025,0,72,fc,0,regular_ll
4,ecmf,z,isobaricInhPa,850,20131025,0,78,fc,0,regular_ll
5,ecmf,z,isobaricInhPa,850,20131025,0,84,fc,0,regular_ll

In [3]:
ds_en.ls()

,centre,shortName,typeOfLevel,level,dataDate,dataTime,stepRange,dataType,number,gridType
0,ecmf,10fg3,surface,0,20131025,0,69-72,cf,0,regular_ll
1,ecmf,10fg3,surface,0,20131025,0,75-78,cf,0,regular_ll
2,ecmf,10fg3,surface,0,20131025,0,81-84,cf,0,regular_ll
3,ecmf,10fg3,surface,0,20131025,0,69-72,pf,1,regular_ll
4,ecmf,10fg3,surface,0,20131025,0,69-72,pf,2,regular_ll
...,...,...,...,...,...,...,...,...,...,...
301,ecmf,z,isobaricInhPa,850,20131025,0,84,pf,46,regular_ll
302,ecmf,z,isobaricInhPa,850,20131025,0,84,pf,47,regular_ll
303,ecmf,z,isobaricInhPa,850,20131025,0,84,pf,48,regular_ll
304,ecmf,z,isobaricInhPa,850,20131025,0,84,pf,49,regular_ll
305,ecmf,z,isobaricInhPa,850,20131025,0,84,pf,50,regular_ll